name: Control Workflow with Metadata

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ls all file
        run: ls -al
      - name: Read metadata
        id: metadata
        run: |
          echo "::set-output name=ENV_NAME::$(jq -r .ENV_NAME metadata.json)"

      - name: Run job based on metadata
        id: metadata-job
        if: ${{ steps.metadata.outputs.ENV_NAME == 'preprod' }}
        run: echo "Creating DEV environment"
