name: Control Workflow with Metadata

on:
  push:
    branches:
      - main

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read metadata
        id: metadata
        run: |
          echo "ENV_NAME=$(jq -r .ENV_NAME metadata.json)" >> $GITHUB_ENV

  job2:
    name: Run job based on metadata
    needs: metadata
    id: metadata-job
    if: ${{ steps.metadata.outputs.ENV_NAME == 'dev' }}
    run: echo "Creating DEV environment"
