name: Control Workflow with Metadata

on:
  push:
    branches:
      - main

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.metadata.outputs.ENV_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Read metadata
        id: metadata
        run: |
          echo "::set-output name=ENV_NAME::$(jq -r .ENV_NAME metadata.json)"

  job2:
    runs-on: ubuntu-latest
    if: ${{ needs.metadata.outputs.env-name == 'dev' }}
    needs: metadata
    steps:
      - name: Run job based on metadata
        run: echo "Creating DEV environment"
