name: Control Workflow with Metadata

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read metadata
        id: metadata
        run: |
          echo "::set-output name=ENV_NAME::$(jq -r .ENV_NAME metadata.json)"

      - name: Run job based on metadata
        if: ${{ steps.metadata.outputs.ENV_NAME == 'dev' }}
        run: echo "Job is enabled!"

      - name: echo jobs
        run: echo "kamlesh"
      # Additional steps for the job go here
